# Generated by Django 4.2.6 on 2023-10-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recording",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=200, unique=True)),
                ("start_time", models.DateTimeField()),
                ("duration", models.IntegerField()),
                ("direction", models.CharField(max_length=1)),
                ("extension", models.CharField(max_length=50)),
                ("agent_id", models.CharField(max_length=50)),
                ("ani", models.CharField(max_length=50)),
                ("dnis", models.CharField(max_length=50)),
                ("custom_data_01", models.CharField(max_length=200)),
                ("custom_data_02", models.CharField(max_length=200)),
                ("custom_data_03", models.CharField(max_length=200)),
            ],
        ),
    ]
